apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-helm
  namespace: openshift-gitops
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: kubernetes-external-secrets
    repoURL: 'https://external-secrets.github.io/kubernetes-external-secrets'
    targetRevision: 8.3.0
